resources:
  - ingress.yaml
  - https-backend-ingress.yaml
  - namespace.yaml
  - package-manage-service.yaml
  - package-manage-service-debug.yaml
  - patch-tracking-service.yaml
  - mailman-api-service.yaml
  - meeting-api-service.yaml
  - bot-debug-service.yaml
  - bot-release-service.yaml
  - euler-icon-service.yaml
  - cve-manager-service.yaml
  - nginx-purger.yaml
  - sync-bot-service.yaml
commonLabels:
  app: openeuler-api
namespace: openeuler-api
