---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: sync-bot-secrets
spec:
  name: sync-bot-secrets
  keysMap:
    secret:
      path: secrets/data/openeuler/sync-bot
      key: secret
    token:
      path: secrets/data/openeuler/sync-bot
      key: token
