kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- namespace.yaml
- deployment.yaml
- pvc.yaml
- service.yaml
- secrets.yaml
- configmap.yaml
commonLabels:
  label: mirrorbits
namespace: repo-mirrorbits
