---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openeuler-data-volume
  annotations: 
    volume.beta.kubernetes.io/storage-class: "ssd"
  labels:
    failure-domain.beta.kubernetes.io/region: ap-southeast-1
    failure-domain.beta.kubernetes.io/zone: ap-southeast-1a
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-volume
  annotations:
    volume.beta.kubernetes.io/storage-class: "ssd"
  labels:
    failure-domain.beta.kubernetes.io/region: ap-southeast-1
    failure-domain.beta.kubernetes.io/zone: ap-southeast-1a
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
