---
apiVersion: v1
kind: Service
metadata:
  name: repo-mirrorbits-service
  namespace: repo-mirrorbits
spec:
  ports:
    - name: repo-mirrorbits-service
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: repo-mirrorbits
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  labels:
    name: redis
  name: redis
spec:
  clusterIP: None
  ports:
  - name: 
    port: 6379
    targetPort: 6379
  selector:
    name: redis
